let
    Origem = Csv.Document(File.Contents("C:\Users\Marcia\Downloads\ANALISTA DE DADOS\People-Analytics-Workforce-Intelligence\00_Dataset_Original\employees_updated.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
    #"Cabeçalhos promovidos" = Table.PromoteHeaders(Origem, [PromoteAllScalars = true]),
    #"Colunas Removidas" = Table.RemoveColumns(#"Cabeçalhos promovidos",{"manager_id", "last_promotion_date"}),
    #"Tipos Texto Data" = Table.TransformColumnTypes(#"Colunas Removidas",{
        {"employee_id", Int64.Type},
        {"first_name", type text},
        {"last_name", type text},
        {"gender", type text},
        {"pronouns", type text},
        {"age", Int64.Type},
        {"birth_date", type date},
        {"department", type text},
        {"business_unit", type text},
        {"job_level", Int64.Type},
        {"job_title", type text},
        {"location", type text},
        {"bonus_eligible", type logical},
        {"equity_grant", type logical},
        {"employment_type", type text},
        {"employment_status", type text},
        {"hire_date", type date},
        {"termination_date", type date},
        {"ethnicity", type text},
        {"marital_status", type text},
        {"education_level", type text},
        {"pay_frequency", type text},
        {"veteran_status", type logical},
        {"disability_status", type logical},
        {"cost_center", type text},
        {"exemption_status", type text},
        {"high_potential_flag", type logical},
        {"succession_plan_status", type text},
        {"aihr_certified", type logical},
        {"training_count", Int64.Type},
        {"last_training_date", type date},
        {"promotion_count", Int64.Type}
    }),
    #"Tipos Decimais" = Table.TransformColumnTypes(#"Tipos Texto Data",{
        {"base_salary", type number},
        {"bonus_pct", type number},
        {"equity_pct", type number},
        {"fte", type number}
    }, "en-US"),
    #"Mesclado" = Table.NestedJoin(#"Tipos Decimais", {"employee_id"}, auxPromocao, {"employee_id"}, "aux", JoinKind.LeftOuter),
    #"Expandido" = Table.ExpandTableColumn(#"Mesclado", "aux", {"foi_promovido", "degraus_promocao"}, {"foi_promovido", "degraus_promocao"})
in
    #"Expandido"